# Generated by Django 5.0.1 on 2024-05-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('carusel_p', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Carusel_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('carusel_p', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Lavita_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('text', models.TextField()),
            ],
        ),
    ]
