# Generated by Django 5.0.1 on 2024-05-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_carusel_carusel_main_lavita_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavita_p',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
