# Generated by Django 5.0.1 on 2024-05-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_alter_lavita_p_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavita_p',
            name='h_text',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
