# Generated by Django 5.0.1 on 2024-05-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_lavita_p_h_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lavita_p',
            old_name='h_text',
            new_name='h1',
        ),
    ]
