# Generated by Django 5.0.1 on 2024-05-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_course_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('events_h1', models.CharField(max_length=100)),
                ('events_p', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('exams_h1', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('exam_li1', models.CharField(blank=True, max_length=200)),
                ('exam_li2', models.CharField(blank=True, max_length=200)),
                ('exam_li3', models.CharField(blank=True, max_length=200)),
                ('exam_li4', models.CharField(blank=True, max_length=200)),
                ('exam_li5', models.CharField(blank=True, max_length=200)),
                ('exam_li6', models.CharField(blank=True, max_length=200)),
                ('exam_li7', models.CharField(blank=True, max_length=200)),
                ('exam_li8', models.CharField(blank=True, max_length=200)),
                ('exam_li9', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('news_h1', models.CharField(max_length=100)),
                ('news_p', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='carusel_main',
            name='title',
            field=models.CharField(default='Default Title', max_length=150),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=15)),
                ('how_many_lesson_in_week', models.CharField(max_length=15)),
                ('how_many_hour', models.CharField(max_length=15)),
                ('lesson_start', models.CharField(max_length=15)),
                ('lesson_finish', models.CharField(max_length=15)),
                ('cost', models.CharField(max_length=30)),
                ('how_many_lesson_in_month', models.CharField(max_length=15)),
                ('how_many_pay', models.CharField(max_length=30)),
                ('course_p', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course_category')),
            ],
        ),
    ]
