# Generated by Django 5.0.1 on 2024-05-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_course_category_event_exam_new_carusel_main_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost_hour',
            field=models.CharField(default='Default Title', max_length=30),
        ),
    ]
