# Generated by Django 5.0.1 on 2024-05-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0008_course_cost_hour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Service_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_h1', models.CharField(max_length=150)),
                ('service_text', models.TextField()),
                ('service_text_in_red', models.CharField(max_length=300)),
            ],
        ),
    ]
