# Generated by Django 5.0.1 on 2024-05-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_service_text_service_text_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exem_level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
                ('words', models.CharField(max_length=30)),
                ('minute', models.CharField(max_length=30)),
                ('level_for_study', models.CharField(max_length=30)),
                ('balls', models.CharField(max_length=30)),
                ('all_balls', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Exem_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_text_1', models.TextField()),
                ('exam_text_2', models.TextField()),
                ('exam_text_3', models.TextField()),
                ('exam_text_4', models.TextField()),
            ],
        ),
    ]
