# Generated by Django 5.0.1 on 2024-05-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_exem_level_exem_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exem_photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
