# Generated by Django 5.0.1 on 2024-05-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_exem_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exem_text_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_text_3', models.TextField()),
            ],
        ),
    ]
