# Generated by Django 5.0.1 on 2024-05-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0014_email_grafic_phone_work_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='grafic',
            name='dont_work_days',
            field=models.CharField(default='ВС', max_length=100),
        ),
    ]
