# Generated by Django 5.0.4 on 2024-05-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0017_remove_exam_exam_li4_remove_exam_exam_li5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='new',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
